server:
  port: 8080

spring:
  application:
    name: resource-processor
  rabbitmq:
    exchange:
      resource-uploaded: x.mp3-resource-uploaded
      resource-processed: x.mp3-resource-processed
    routingkey:
      resource-uploaded: rk.mp3-resource-uploaded
      resource-processed: rk.mp3-resource-processed
    queue:
      resource-uploaded: q.mp3-resource-uploaded
  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true