{
 "title": "Process mp3 metadata",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:250%;font-weight:bold;color:#EEF27E;\">PROCESS MP3 METADATA</p>"
   }
  },
  {
   "title": "Average Process mp3 Listener",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(process_mp3_full_seconds_sum[1m]) / increase(process_mp3_full_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process mp3 metadata Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "increase(process_mp3_metadata_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Process mp3 metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(process_mp3_metadata_seconds_sum[1m])/ increase(process_mp3_metadata_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "mp3 file size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "mp3_file_size", "legendFormat": "__auto" }
   ]
  }
 ]
}