{
 "title": "Upload Resource",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:250%;font-weight:bold;color:#EEF27E;\">UPLOAD MP3</p>"
   }
  },
  {
   "title": "Upload mp3 Full process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "increase(upload_mp3_full_seconds_sum[1m]) / increase(upload_mp3_full_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload mp3 Time per upload",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "increase(upload_mp3_full_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Process mp3 metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "increase(upload_mp3_to_staging_seconds_sum[1m]) / increase(upload_mp3_to_staging_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Move mp3 to PERMANENT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(move_mp3_to_permanent_seconds_sum[1m]) / increase(move_mp3_to_permanent_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload mp3 to STAGING counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "upload_mp3_to_staging_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload mp3 to PERMANENT counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "upload_mp3_to_permanent_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted mp3 from STAGING counter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "deleted_mp3_from_staging_counter_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}