server:
  port: 8086

app:
  staging-bucket: a-lautsou-resources-storage-staging
  permanent-bucket: a-lautsou-resources-storage-permanent
  oauth2:
    signing-key: 123

aws:
  region: us-east-1

spring:
  application:
    name: storage-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5003/storagesDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        clientId: storage-client
        clientSecret: noonewilleverguess
      resource:
        tokenInfoUri: http://localhost:8079/oauth/check_token

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true